image: python:latest

stages:
  - deploy

deploy_to_dockerhub:
  stage: deploy
  only:
    refs:
      - master
  except:
    - tags
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
    - docker buildx create --use
  script:
    - docker buildx build --push --tag rogsme/bitwarden-to-keepass:latest .

deploy_to_gitlab:
  stage: deploy
  only:
    refs:
      - master
  except:
    - tags
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - echo "$GITLAB_PASSWORD" | docker login registry.gitlab.com -u "$GITLAB_USERNAME" --password-stdin
    - docker buildx create --use
  script:
    - docker buildx build --push --tag registry.gitlab.com/rogs/bitwarden-to-keepass:latest .
