name: Deploy to DockerHub & Gitea

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  deploy:
    runs-on: docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Log in to Gitea Registry
        run: echo "${{ secrets.GITEA_REGISTRY_TOKEN }}" | docker login git.rogs.me -u rogs --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push to Dockerhub and git.rogs.me
        run: |
          docker buildx build --push \
            --tag rogsme/bitwarden-to-keepass:latest \
            --tag git.rogs.me/rogs/bitwarden-to-keepass:latest \
            .
